services:
  db:
      image: postgres:16.2-alpine3.18
      restart: always
      environment:
        POSTGRES_PASSWORD: todo123
        POSTGRES_USER: todouser
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 60s
        timeout: 5s
        retries: 3
      ports:
        - "5432:5432"
      volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: julian@local.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data: